version: "3"

services:
  domain_db:
    image: postgres
    container_name: "domain"
    environment:
      POSTGRES_PASSWORD: "abc123"
      POSTGRES_USER: "domain"
      POSTGRES_DB: "domains"

    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"