version: 0.2

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=006375924004.dkr.ecr.us-east-1.amazonaws.com/spaces-domain-service
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_BUILD_NUMBER | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - '*'
    - 'infrastructure/ecs/service-labs.json'
    - 'infrastructure/ecs/service-prod.json'
  base-directory: .
  discard-paths: no